version: '3.3'
services:
  elasticsearch:
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx2G -Xms2G"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  logstash:
    volumes:
      - /data/logstash:/usr/share/logstash/data/
    image: logstash-custom:6.8.1
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline_logstash
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash_pipeline_alb
        target: /usr/share/logstash/pipeline/alb.conf
      - source: logstash_pipeline_slack
        target: /usr/share/logstash/pipeline/slack.conf
    environment:
      LS_JAVA_OPTS: "-Xmx1G -Xms1G"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
configs:
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline_logstash:
    file: ./logstash/pipeline/logstash.conf
  logstash_pipeline_alb:
    file: ./logstash/pipeline/alb.conf
  logstash_pipeline_slack:
    file: ./logstash/pipeline/slack.conf
  kibana_config:
    file: ./kibana/config/kibana.yml
networks:
  elk:
    driver: overlay
